//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventPhotos = new HashSet<EventPhoto>();
            this.OrganizationParticipations = new HashSet<OrganizationParticipation>();
            this.ParticipationRequests = new HashSet<ParticipationRequest>();
            this.StudentParticipations = new HashSet<StudentParticipation>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int EventID { get; set; }
        public int StudyPeriodID { get; set; }
        public int DirectionID { get; set; }
        public string Name { get; set; }
        public System.DateTime EventDate { get; set; }
        public System.TimeSpan EventTime { get; set; }
        public string Place { get; set; }
        public Nullable<int> ExpectedStudentsAmount { get; set; }
        public Nullable<int> ActualStudentsAmount { get; set; }
        public Nullable<int> Scores { get; set; }
    
        public virtual Direction Direction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPhoto> EventPhotos { get; set; }
        public virtual StudyPeriod StudyPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationParticipation> OrganizationParticipations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationRequest> ParticipationRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentParticipation> StudentParticipations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
