//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPhoto
    {
        public int PhotoID { get; set; }
        public int EventID { get; set; }
        public string PhotoLink { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
