//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalOrganization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalOrganization()
        {
            this.OrganizationParticipations = new HashSet<OrganizationParticipation>();
        }
    
        public int OrganizationID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string RepresentativeFullName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationParticipation> OrganizationParticipations { get; set; }
    }
}
