//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationParticipation
    {
        public int ParttakeID { get; set; }
        public int OrganizationID { get; set; }
        public int EventID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ExternalOrganization ExternalOrganization { get; set; }
    }
}
