//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationRequest
    {
        public int RequestID { get; set; }
        public int StudentID { get; set; }
        public int EventID { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Student Student { get; set; }
    }
}
