//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentCouncilAppEntities : DbContext
    {
        public StudentCouncilAppEntities()
            : base("name=StudentCouncilAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Direction> Directions { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<EventPhoto> EventPhotos { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<ExternalOrganization> ExternalOrganizations { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<OrganizationParticipation> OrganizationParticipations { get; set; }
        public virtual DbSet<ParticipationRequest> ParticipationRequests { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<StudentParticipation> StudentParticipations { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudyPeriod> StudyPeriods { get; set; }
        public virtual DbSet<Supervisor> Supervisors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
