//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCouncilApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supervisor
    {
        public int SupervisorID { get; set; }
        public int DirectionID { get; set; }
        public int StudentID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Student Student { get; set; }
    }
}
